services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql9
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./datadir:/var/lib/mysql
    restart: unless-stopped